name: Test Project
on: push
jobs:
  test:
    runs-on: ubtuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS # ubuntu comes with node preinstalled, this is just for practice purposes
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npm test
